sudo: required # super user permission
services:
  - docker


before_install:
  - docker build -t sunnymean/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true sunnymean/docker-react npm run test -- --coverage
